#!/bin/bash

if ! command -v mvn &> /dev/null #checks if maven is installed
then
    echo "Maven is not installed. Spotless will not be checked"
    exit 0
fi

#prevents the shell from aborting if maven returns a non zero exit code
set +e

echo Checking spotless
mvn spotless:check &> /dev/null
exitCode=$?

if [ $exitCode -gt 0 ]
then
	echo "Spotless failed. Please run 'mvn spotless:apply' to fix."
	exit 1
fi

echo Running Checkstyle
mvn checkstyle:check &> /dev/null
exitCode=$?

if [ $exitCode -gt 0 ]
then
  echo "Checkstyle failed. Please run 'mvn checkstyle:check' to get a list of issues."
  exit 1
fi

exit 0
