name: Report Viewer Unit Test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/report-viewer-test-unit.yml"
      - "report-viewer/**"

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'same_content_newer'
          skip_after_successful_duplicate: 'true'

  test:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"

      - name: Install and run tests and merge-reports
        id: generate
        working-directory: report-viewer
        run: |
          npm install
          npm run test:coverage
          npm run merge-coverage
      
      - name: Post comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const path = require('path');
            const basePath = path.join(process.cwd(), 'report-viewer/coverage/');
            const summaryPath = path.join(basePath, 'summary.txt');
            const detailPath = path.join(basePath, 'detail.txt');

            const summaryContent = fs.readFileSync(summaryPath, 'utf8').trim();
            const detailContent = fs.readFileSync(detailPath, 'utf8').trim();
            const body = `\`\`\`
            ${summaryContent}
            \`\`\`
            <details>
            <summary>Per File Coverage</summary>
            </details>`
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })

      - name: Fail on low coverage
        run: |
          echo "Coverage: ${{ steps.generate.outputs.COVERAGE }}"
          if [ ${{ steps.generate.outputs.COVERAGE }} -lt 50 ]; then
            exit 1
          fi
