name: Report Viewer Unit Test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/report-viewer-test-unit.yml"
      - "report-viewer/**"

permissions:
  issues: write
  pull-requests: write 

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'same_content_newer'
          skip_after_successful_duplicate: 'true'

  test:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"

      - name: Install and run tests and merge-reports
        id: generate
        working-directory: report-viewer
        env:
          COLUMNS: 120
        run: |
          npm install
          npm run test:coverage
          npm run merge-coverage
          echo "$GITHUB_OUTPUT"
      
      - name: Post comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const comments = await github.paginate(
                github.issues.listComments,
                {
                  owner: "Kr0nox",
                  repo: "JPlag",
                  issue_number: 3,
                  per_page: 100,
                }
              )
            console.log(comments, comments[0], comments[1])

            const fs = require('fs');
            const path = require('path');
            const basePath = path.join(process.cwd(), 'report-viewer/coverage/');
            const summaryPath = path.join(basePath, 'summary.txt');
            const detailPath = path.join(basePath, 'detail.txt');

            const summaryContent = fs.readFileSync(summaryPath, 'utf8').trim();
            const detailContent = fs.readFileSync(detailPath, 'utf8').trim();
            const body = `\`\`\`
            ${summaryContent}
            \`\`\`
            <details>
            <summary>Per File Coverage</summary>

            \`\`\`
            ${detailContent}
            \`\`\`
            </details>`
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })

      - name: Upload coverage results
        uses: actions/upload-artifact@v6
        with:
          name: "coverage-report"
          path: report-viewer/coverage/html
          retention-days: 30

      - name: Fail on low coverage
        env:
          COVERAGE: ${{ steps.generate.outputs.COVERAGE }}
        run: |
          echo "Coverage: ${{ steps.generate.outputs.COVERAGE }}"
          if [ $(bc <<< "$COVERAGE < 20.0") -eq 1 ]; then
            exit 1
          fi
